name: Node.js CI

on: [push]

jobs:
    builds:
        strategy:
            matrix:
                platform: [ubuntu-latest, macos-latest, windows-latest]
                node-version: [12.x]
            fail-fast: false

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v2
              name: Use Node.js ${{ matrix.node-version }}
              with:
                  node-version: ${{ matrix.node-version }}

            - run: |
                  npm install
                  npm run test
